// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUAx7LUrgpMM7qEa1vNpMms2Rrfn2IsU4',
    appId: '1:616284719617:web:1d90076224448640ae8e00',
    messagingSenderId: '616284719617',
    projectId: 'fir-5a38d',
    authDomain: 'fir-5a38d.firebaseapp.com',
    storageBucket: 'fir-5a38d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiZBPDi2y7Nde0zf3onOWM5-p377hcq8s',
    appId: '1:616284719617:android:1fd676ff6ba918f6ae8e00',
    messagingSenderId: '616284719617',
    projectId: 'fir-5a38d',
    storageBucket: 'fir-5a38d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoATXP6Hufm0cNJjXHx1ARjEulhcRiFRY',
    appId: '1:616284719617:ios:7f454eb32cad749dae8e00',
    messagingSenderId: '616284719617',
    projectId: 'fir-5a38d',
    storageBucket: 'fir-5a38d.appspot.com',
    iosBundleId: 'com.example.trackerApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoATXP6Hufm0cNJjXHx1ARjEulhcRiFRY',
    appId: '1:616284719617:ios:46b7a8c9868e0b7fae8e00',
    messagingSenderId: '616284719617',
    projectId: 'fir-5a38d',
    storageBucket: 'fir-5a38d.appspot.com',
    iosBundleId: 'com.example.trackerApplication.RunnerTests',
  );
}
